name: Nix Flake CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Nix Flake CI - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Build flake
        run: nix build --print-build-logs nix

      - name: Check flake
        run: nix flake check 'path:nix'
